# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='cardNumber',
            field=models.IntegerField(default=0),
        ),
    ]
