# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180718_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Person'),
        ),
    ]
